//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTH5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongTrinh()
        {
            this.Congs = new HashSet<Cong>();
        }
    
        public int MaCT { get; set; }
        public string TenCT { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<System.DateTime> NgayCapGP { get; set; }
        public Nullable<System.DateTime> NgayKC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cong> Congs { get; set; }
    }
}
