//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTH5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cong> Congs { get; set; }
        public virtual DbSet<CongTrinh> CongTrinhs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
    
        [DbFunction("DBContext", "GetNhanVien")]
        public virtual IQueryable<GetNhanVien_Result> GetNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetNhanVien_Result>("[DBContext].[GetNhanVien]()");
        }
    
        [DbFunction("DBContext", "GetNhanVienByDiaChi")]
        public virtual IQueryable<GetNhanVienByDiaChi_Result> GetNhanVienByDiaChi(string diachi)
        {
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetNhanVienByDiaChi_Result>("[DBContext].[GetNhanVienByDiaChi](@diachi)", diachiParameter);
        }
    
        [DbFunction("DBContext", "GetNhanVienByGioiTinh")]
        public virtual IQueryable<GetNhanVienByGioiTinh_Result> GetNhanVienByGioiTinh(string gioitinh)
        {
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetNhanVienByGioiTinh_Result>("[DBContext].[GetNhanVienByGioiTinh](@gioitinh)", gioitinhParameter);
        }
    
        [DbFunction("DBContext", "GetNhanVienByTen")]
        public virtual IQueryable<GetNhanVienByTen_Result> GetNhanVienByTen(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetNhanVienByTen_Result>("[DBContext].[GetNhanVienByTen](@ten)", tenParameter);
        }
    
        [DbFunction("DBContext", "GetNhanVietByDoTuoi")]
        public virtual IQueryable<GetNhanVietByDoTuoi_Result> GetNhanVietByDoTuoi(Nullable<int> min, Nullable<int> max)
        {
            var minParameter = min.HasValue ?
                new ObjectParameter("min", min) :
                new ObjectParameter("min", typeof(int));
    
            var maxParameter = max.HasValue ?
                new ObjectParameter("max", max) :
                new ObjectParameter("max", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetNhanVietByDoTuoi_Result>("[DBContext].[GetNhanVietByDoTuoi](@min, @max)", minParameter, maxParameter);
        }
    
        [DbFunction("DBContext", "GetPhongBan")]
        public virtual IQueryable<GetPhongBan_Result> GetPhongBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPhongBan_Result>("[DBContext].[GetPhongBan]()");
        }
    
        public virtual int AddCong(Nullable<int> maCT, Nullable<int> maNV, Nullable<int> sLNgayCong)
        {
            var maCTParameter = maCT.HasValue ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var sLNgayCongParameter = sLNgayCong.HasValue ?
                new ObjectParameter("SLNgayCong", sLNgayCong) :
                new ObjectParameter("SLNgayCong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCong", maCTParameter, maNVParameter, sLNgayCongParameter);
        }
    
        public virtual int AddCongTrinh(string ten, string diadiem, Nullable<System.DateTime> ngaycap, Nullable<System.DateTime> ngaykc)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var diadiemParameter = diadiem != null ?
                new ObjectParameter("diadiem", diadiem) :
                new ObjectParameter("diadiem", typeof(string));
    
            var ngaycapParameter = ngaycap.HasValue ?
                new ObjectParameter("ngaycap", ngaycap) :
                new ObjectParameter("ngaycap", typeof(System.DateTime));
    
            var ngaykcParameter = ngaykc.HasValue ?
                new ObjectParameter("ngaykc", ngaykc) :
                new ObjectParameter("ngaykc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCongTrinh", tenParameter, diadiemParameter, ngaycapParameter, ngaykcParameter);
        }
    
        public virtual int AddNhanVien(Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChi, Nullable<int> maPB)
        {
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddNhanVien", ngaySinhParameter, gioiTinhParameter, diaChiParameter, maPBParameter);
        }
    
        public virtual int AddPhongBan(string tenpb)
        {
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPhongBan", tenpbParameter);
        }
    
        public virtual int DeleteCong(Nullable<int> mact, Nullable<int> maNV)
        {
            var mactParameter = mact.HasValue ?
                new ObjectParameter("Mact", mact) :
                new ObjectParameter("Mact", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCong", mactParameter, maNVParameter);
        }
    
        public virtual int DeleteCongTrinh(Nullable<int> mact)
        {
            var mactParameter = mact.HasValue ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCongTrinh", mactParameter);
        }
    
        public virtual int DeleteNhanVien(Nullable<int> maNV)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteNhanVien", maNVParameter);
        }
    
        public virtual int DeletePhongBan(Nullable<int> mapb)
        {
            var mapbParameter = mapb.HasValue ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePhongBan", mapbParameter);
        }
    
        public virtual int UpdateCong(Nullable<int> maCT, Nullable<int> maNV, Nullable<int> sLNgayCong)
        {
            var maCTParameter = maCT.HasValue ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var sLNgayCongParameter = sLNgayCong.HasValue ?
                new ObjectParameter("SLNgayCong", sLNgayCong) :
                new ObjectParameter("SLNgayCong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCong", maCTParameter, maNVParameter, sLNgayCongParameter);
        }
    
        public virtual int UpdateCongTrinh(Nullable<int> mact, string ten, string diadiem, Nullable<System.DateTime> ngaycap, Nullable<System.DateTime> ngaykc)
        {
            var mactParameter = mact.HasValue ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var diadiemParameter = diadiem != null ?
                new ObjectParameter("diadiem", diadiem) :
                new ObjectParameter("diadiem", typeof(string));
    
            var ngaycapParameter = ngaycap.HasValue ?
                new ObjectParameter("ngaycap", ngaycap) :
                new ObjectParameter("ngaycap", typeof(System.DateTime));
    
            var ngaykcParameter = ngaykc.HasValue ?
                new ObjectParameter("ngaykc", ngaykc) :
                new ObjectParameter("ngaykc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCongTrinh", mactParameter, tenParameter, diadiemParameter, ngaycapParameter, ngaykcParameter);
        }
    
        public virtual int UpdateNhanVien(Nullable<int> maNV, Nullable<System.DateTime> ngaySinh, string gioiTinh, string diaChi, Nullable<int> maPB)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var maPBParameter = maPB.HasValue ?
                new ObjectParameter("MaPB", maPB) :
                new ObjectParameter("MaPB", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateNhanVien", maNVParameter, ngaySinhParameter, gioiTinhParameter, diaChiParameter, maPBParameter);
        }
    
        public virtual int UpdatePhongBan(Nullable<int> mapb, string tenpb)
        {
            var mapbParameter = mapb.HasValue ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(int));
    
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePhongBan", mapbParameter, tenpbParameter);
        }
    
        [DbFunction("DBContext", "GetNhanVienByPhongBan")]
        public virtual IQueryable<GetNhanVienByPhongBan_Result> GetNhanVienByPhongBan(string tenpb)
        {
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetNhanVienByPhongBan_Result>("[DBContext].[GetNhanVienByPhongBan](@tenpb)", tenpbParameter);
        }
    }
}
